### ISSUE TITLE
No HMD found in: eDP1 1600x900 21.4cmx38.2cm AUO 0x159e Built-in display

### ISSUE THREAD

**Issue by tamimcse** [lubosz/gst-plugins-vr#10]
**./sphvr/sphvr file:///home/bmonkey/video.webm** gives following error:

No HMD found in:
eDP1 1600x900 21.4cmx38.2cm AUO 0x159e Built-in display
Traceback (most recent call last):
  File "./sphvr/sphvr", line 238, in <module>
    SPHVR()
  File "./sphvr/sphvr", line 89, in __init__
    self.init_pipeline()
  File "./sphvr/sphvr", line 167, in init_pipeline
    self.pipeline.add(src, glupload, glcolorconvert, videorate)
TypeError: Gst.Bin.add() takes exactly 2 arguments (5 given)

Yes, I don't have a HMD and Kinect. I just want to play a pre-recorded Kinect video on my laptop. Is it possible? If so, could you also provide me with a sample video that I can play with?

Many thanks!

**Comment by lubosz** [comment]
> file:///home/bmonkey/video.webm

You probably should use a file that exists on your system.

> I don't have a HMD

Well the error message is correct then, no? :)

> I just want to play a pre-recorded Kinect video on my laptop. Is it possible?

What format is the video in? You probably will be able to play back the recorded depth buffer, but the visualization implementation (gstpointcloudbuilder) is still WIP.
It is another issue then

> TypeError: Gst.Bin.add() takes exactly 2 arguments (5 given)

This exception should probably fixed

**Comment by tamimcse** [comment]
I need to stream Kinect video. Currently I don't have a Kinect. Is there a way I can generate test video? I'm also wondering if there is an MPEG extension for kinect video (3D video).
